name: cadvisor Image CI
env:
  IMAGE_VERSION: v0.47.2
  DOCKER_IMAGE_NAME: gematt/cadvisor

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: Generate Docker metadata
    #   id: meta
    #   uses: docker/metadata-action@v3
    #   with:
    #     images: |
    #       docker.io/${{ env.DOCKER_IMAGE_NAME }}
    #     tags: | 
    #       type=ref,event=branch
    #       type=semver,pattern=${{ env.IMAGE_VERSION }}
    
    - name: Login to docker hub
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Image
      run: docker build -f cadvisor/Dockerfile -t ${{ DOCKER_IMAGE_NAME }}:${{ IMAGE_VERSION }} .

    - name: Push Image
      run: docker push  ${{ DOCKER_IMAGE_NAME }}:${{ IMAGE_VERSION }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v4.0.0
    #   with:
    #     context: .
    #     file: cadvisor/Dockerfile
    #     push: true
    #     tags: ${{ env.IMAGE_VERSION }}
          
