name: cadvisor Image CI
env:
  CADVISOR_BASE_IMAGE: gcr.io/cadvisor/cadvisor:v0.47.2
  DOCKER_IMAGE_NAME: gematt/cadvisor:v0.47.2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: Generate Docker metadata
    #   id: meta
    #   uses: docker/metadata-action@v3
    #   with:
    #     images: |
    #       docker.io/${{ env.DOCKER_IMAGE_NAME }}
    #     tags: | 
    #       type=ref,event=branch
    #       type=semver,pattern=${{ env.IMAGE_VERSION }}
    
    - name: Login to docker hub
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # - name: Build Image
    #   run: docker build -f cadvisor/Dockerfile -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_VERSION }} .

    - name: Pull Base Image
      run: docker pull ${{ env.CADVISOR_BASE_IMAGE }}

    - name: Tag Image
      run: docker tag ${{ env.CADVISOR_BASE_IMAGE }} ${{ env.DOCKER_IMAGE_NAME }}

    - name: Push Image
      run: docker push  ${{ env.DOCKER_IMAGE_NAME }}

          
